// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://yourdomain.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://yourdomain.com/support",
            "email": "support@yourdomain.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/reports/exports": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Queue an export for approved submissions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "Create report export",
                "parameters": [
                    {
                        "description": "Export payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.CreateReportExportRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.ReportExport"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/review-submissions": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "List all pending and processed review submissions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "List review submissions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.ReviewSubmission"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/admin/review-submissions/{submission_id}/decision": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Save an admin decision and final scorecard for a submission",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "Record review decision",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Submission ID",
                        "name": "submission_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Decision payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.ReviewDecisionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.AdminReview"
                        }
                    }
                }
            }
        },
        "/api/v1/healthcheck": {
            "get": {
                "description": "Returns the application health status and dependency checks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@healthcheck"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_healthcheck.HealthCheckResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_healthcheck.HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/healthcheck/liveness": {
            "get": {
                "description": "Returns whether the process is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@healthcheck"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_healthcheck.LivenessResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/healthcheck/readiness": {
            "get": {
                "description": "Returns whether the service is ready to serve traffic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@healthcheck"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_healthcheck.ReadinessResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/projects": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "List projects visible to the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "List projects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.Project"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Create a new scientific TZ project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "Create project",
                "parameters": [
                    {
                        "description": "Project payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.CreateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.Project"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{project_id}": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Get project by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "Get project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.Project"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{project_id}/chat-sessions": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Create a project-bound chat session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "Create chat session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Chat session payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.CreateChatSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.ChatSession"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{project_id}/chat-sessions/{session_id}/messages": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Send a chat message and store the AI response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "Send chat message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Chat message payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.SendChatMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.SendChatMessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{project_id}/submit-for-review": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Create a review submission for a project version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "Submit for review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Review submission payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.SubmitForReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.ReviewSubmission"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{project_id}/versions": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "List document versions for a project",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "List versions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.DocumentVersion"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Create a new document version from an uploaded file asset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "Create version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Version payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.CreateVersionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.DocumentVersion"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{project_id}/versions/{version_id}/analysis/latest": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Get the latest stored analysis for a document version",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "Latest analysis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version ID",
                        "name": "version_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.LatestAnalysisResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{project_id}/versions/{version_id}/analyze": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Send a document version to AI-service and persist the analysis",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@tzworkflow"
                ],
                "summary": "Analyze version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version ID",
                        "name": "version_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.LatestAnalysisResponse"
                        }
                    }
                }
            }
        },
        "/assets": {
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Uploads a file for the authenticated applicant and creates an unattached application file record.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@assets"
                ],
                "summary": "Upload asset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File type",
                        "name": "file_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Binary file payload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_assets.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/assets/{id}": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Returns the uploaded asset binary payload for the owning applicant or admin reviewer.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "@assets"
                ],
                "summary": "Get uploaded asset by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticates a user and returns access and refresh tokens. When email verification is enabled, the user must be verified.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@auth"
                ],
                "summary": "Login with email and password",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.TokenResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Revokes the provided refresh token session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@auth"
                ],
                "summary": "Logout current refresh session",
                "parameters": [
                    {
                        "description": "Logout payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.LogoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Returns the current user profile extracted from the bearer access token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@auth"
                ],
                "summary": "Get current authenticated user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.meResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Rotates the refresh session and returns a new access and refresh token pair.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh token payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.TokenResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Creates a new user account and conditionally issues an email verification code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@auth"
                ],
                "summary": "Register applicant account",
                "parameters": [
                    {
                        "description": "Registration payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/resend-code": {
            "post": {
                "description": "Issues a new verification code for an existing unverified user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@auth"
                ],
                "summary": "Resend email verification code",
                "parameters": [
                    {
                        "description": "Resend code payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.ResendCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/verify-email": {
            "post": {
                "description": "Verifies a user's email address using the latest active verification code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@auth"
                ],
                "summary": "Verify email with code",
                "parameters": [
                    {
                        "description": "Email verification payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.VerifyEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the application health status and dependency checks.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@healthcheck"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_healthcheck.HealthCheckResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_healthcheck.HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/health/liveness": {
            "get": {
                "description": "Returns whether the process is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@healthcheck"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_healthcheck.LivenessResponse"
                        }
                    }
                }
            }
        },
        "/health/readiness": {
            "get": {
                "description": "Returns whether the service is ready to serve traffic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "@healthcheck"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_healthcheck.ReadinessResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ai.AnalyzeResponse": {
            "type": "object",
            "properties": {
                "ai_document_analysis_scorecard": {
                    "$ref": "#/definitions/ai.Scorecard"
                },
                "ai_preliminary_evaluation_scorecard": {
                    "$ref": "#/definitions/ai.Scorecard"
                },
                "analysis_status": {
                    "type": "string"
                },
                "confirmed_entities": {
                    "$ref": "#/definitions/ai.NotebookEntityBundle"
                },
                "detected_sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.Section"
                    }
                },
                "document": {
                    "$ref": "#/definitions/ai.DocumentMetadata"
                },
                "extracted_entities": {
                    "$ref": "#/definitions/ai.NotebookEntityBundle"
                },
                "findings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.Finding"
                    }
                },
                "generate_improved_tz": {
                    "$ref": "#/definitions/ai.NotebookImprovedTZ"
                },
                "improved_text": {
                    "type": "string"
                },
                "improved_tz": {
                    "type": "string"
                },
                "missing_required_sections": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "model_metadata": {
                    "$ref": "#/definitions/ai.ModelMetadata"
                },
                "raw_text_preview": {
                    "type": "string"
                },
                "recommendations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.Recommendation"
                    }
                },
                "score": {
                    "$ref": "#/definitions/ai.NotebookScore"
                },
                "semantic": {
                    "$ref": "#/definitions/ai.NotebookSemantic"
                },
                "structure": {
                    "$ref": "#/definitions/ai.NotebookStructure"
                },
                "suggested_structure": {
                    "type": "string"
                },
                "weak_sections": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "ai.ChatResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "referenced_findings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "referenced_sections": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "response_status": {
                    "type": "string"
                },
                "suggested_next_actions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "ai.DocumentMetadata": {
            "type": "object",
            "properties": {
                "character_count": {
                    "type": "integer"
                },
                "content_type": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "parser": {
                    "type": "string"
                }
            }
        },
        "ai.Finding": {
            "type": "object",
            "properties": {
                "explanation": {
                    "type": "string"
                },
                "finding_type": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "recommendation": {
                    "type": "string"
                },
                "section_key": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                }
            }
        },
        "ai.ModelMetadata": {
            "type": "object",
            "properties": {
                "mode": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "prompt_version": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "ai.NotebookEntity": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number"
                },
                "section": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "ai.NotebookEntityBundle": {
            "type": "object",
            "properties": {
                "deadlines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.NotebookEntity"
                    }
                },
                "expected_results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.NotebookEntity"
                    }
                },
                "kpis": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.NotebookEntity"
                    }
                },
                "requirements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.NotebookEntity"
                    }
                }
            }
        },
        "ai.NotebookImprovedTZ": {
            "type": "object",
            "properties": {
                "improved_text": {
                    "type": "string"
                },
                "summary_of_changes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "ai.NotebookScore": {
            "type": "object",
            "properties": {
                "breakdown": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                },
                "explanation": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_score": {
                    "type": "number"
                }
            }
        },
        "ai.NotebookSemantic": {
            "type": "object",
            "properties": {
                "ambiguities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.NotebookSemanticIssue"
                    }
                },
                "contradictions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.NotebookSemanticIssue"
                    }
                },
                "deadlines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.NotebookSemanticIssue"
                    }
                },
                "expected_results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.NotebookSemanticIssue"
                    }
                },
                "kpis": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.NotebookSemanticIssue"
                    }
                },
                "missing_elements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.NotebookSemanticIssue"
                    }
                },
                "requirements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.NotebookSemanticIssue"
                    }
                }
            }
        },
        "ai.NotebookSemanticIssue": {
            "type": "object",
            "properties": {
                "explanation": {
                    "type": "string"
                },
                "issue_type": {
                    "type": "string"
                },
                "quote": {
                    "type": "string"
                },
                "recommendation": {
                    "type": "string"
                },
                "section": {
                    "type": "string"
                }
            }
        },
        "ai.NotebookStructure": {
            "type": "object",
            "properties": {
                "empty_sections": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "found_sections": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "matched_required_sections": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "missing_sections": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.NotebookStructureSection"
                    }
                },
                "weak_sections": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "ai.NotebookStructureSection": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "length": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "ai.Recommendation": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "ai.Scorecard": {
            "type": "object",
            "properties": {
                "is_placeholder": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ai.ScorecardItem"
                    }
                },
                "max_total_score": {
                    "type": "number"
                },
                "score_type": {
                    "type": "string"
                },
                "total_score": {
                    "type": "number"
                }
            }
        },
        "ai.ScorecardItem": {
            "type": "object",
            "properties": {
                "explanation": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "max_score": {
                    "type": "number"
                },
                "score": {
                    "type": "number"
                }
            }
        },
        "ai.Section": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number"
                },
                "content_excerpt": {
                    "type": "string"
                },
                "end_index": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "start_index": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_assets.Response": {
            "type": "object",
            "properties": {
                "file_id": {
                    "type": "string"
                },
                "file_type": {
                    "type": "string"
                },
                "original_filename": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.LogoutRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "requires_email_verification": {
                    "type": "boolean"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.ResendCodeRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.ResponseUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_email_verified": {
                    "type": "boolean"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in_seconds": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.ResponseUser"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.VerifyEmailRequest": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.meResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_auth.ResponseUser"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_healthcheck.CheckResult": {
            "type": "object",
            "properties": {
                "latency": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_healthcheck.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_healthcheck.CheckResult"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_healthcheck.LivenessResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_healthcheck.ReadinessResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.AdminReview": {
            "type": "object",
            "properties": {
                "decision": {
                    "type": "string"
                },
                "expert_report_comment": {
                    "type": "string"
                },
                "final_scorecard_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "review_feedback": {
                    "type": "string"
                },
                "review_submission_id": {
                    "type": "string"
                },
                "reviewed_at": {
                    "type": "string"
                },
                "reviewed_by_user_id": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.ChatMessage": {
            "type": "object",
            "properties": {
                "chat_session_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata_json": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.ChatSession": {
            "type": "object",
            "properties": {
                "analysis_run_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by_user_id": {
                    "type": "string"
                },
                "document_version_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.CreateChatSessionRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string",
                    "minLength": 2
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.CreateProjectRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "organization_name": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "minLength": 2
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.CreateReportExportRequest": {
            "type": "object",
            "required": [
                "export_type",
                "review_submission_ids"
            ],
            "properties": {
                "export_type": {
                    "type": "string"
                },
                "review_submission_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.CreateVersionRequest": {
            "type": "object",
            "required": [
                "file_id"
            ],
            "properties": {
                "file_id": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.DocumentVersion": {
            "type": "object",
            "properties": {
                "analysis_run_id": {
                    "type": "string"
                },
                "analysis_status": {
                    "type": "string"
                },
                "content_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "extraction_status": {
                    "type": "string"
                },
                "file_size_bytes": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "original_file_id": {
                    "type": "string"
                },
                "original_filename": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "raw_text_preview": {
                    "type": "string"
                },
                "uploaded_by_user_id": {
                    "type": "string"
                },
                "version_number": {
                    "type": "integer"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.LatestAnalysisResponse": {
            "type": "object",
            "properties": {
                "analysis": {
                    "$ref": "#/definitions/ai.AnalyzeResponse"
                },
                "analysis_run_id": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.Project": {
            "type": "object",
            "properties": {
                "active_version_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "final_version_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "organization_name": {
                    "type": "string"
                },
                "owner_user_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.ReportExport": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by_user_id": {
                    "type": "string"
                },
                "export_type": {
                    "type": "string"
                },
                "file_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.ReviewDecisionRequest": {
            "type": "object",
            "required": [
                "decision"
            ],
            "properties": {
                "decision": {
                    "type": "string",
                    "enum": [
                        "approved",
                        "rejected",
                        "needs_revision"
                    ]
                },
                "expert_report_comment": {
                    "type": "string"
                },
                "final_scorecard": {
                    "$ref": "#/definitions/ai.Scorecard"
                },
                "review_feedback": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.ReviewSubmission": {
            "type": "object",
            "properties": {
                "document_version_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                },
                "submitted_by_user_id": {
                    "type": "string"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.SendChatMessageRequest": {
            "type": "object",
            "required": [
                "user_message"
            ],
            "properties": {
                "user_message": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.SendChatMessageResponse": {
            "type": "object",
            "properties": {
                "ai_response": {
                    "$ref": "#/definitions/ai.ChatResponse"
                },
                "assistant_message": {
                    "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.ChatMessage"
                },
                "session_id": {
                    "type": "string"
                },
                "user_message": {
                    "$ref": "#/definitions/github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.ChatMessage"
                }
            }
        },
        "github.com_agentic-lab-club_Satpayev_science_tz_hackaton_backend_internal_tzworkflow.SubmitForReviewRequest": {
            "type": "object",
            "properties": {
                "document_version_id": {
                    "type": "string"
                }
            }
        },
        "internal_assets.Response": {
            "type": "object",
            "properties": {
                "file_id": {
                    "type": "string"
                },
                "file_type": {
                    "type": "string"
                },
                "original_filename": {
                    "type": "string"
                }
            }
        },
        "internal_auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        },
        "internal_auth.LogoutRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_auth.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_auth.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "internal_auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        },
        "internal_auth.RegisterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "requires_email_verification": {
                    "type": "boolean"
                }
            }
        },
        "internal_auth.ResendCodeRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "internal_auth.ResponseUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_email_verified": {
                    "type": "boolean"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "internal_auth.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in_seconds": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/internal_auth.ResponseUser"
                }
            }
        },
        "internal_auth.VerifyEmailRequest": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "internal_auth.meResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/internal_auth.ResponseUser"
                }
            }
        },
        "internal_healthcheck.CheckResult": {
            "type": "object",
            "properties": {
                "latency": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_healthcheck.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/internal_healthcheck.CheckResult"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "internal_healthcheck.LivenessResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_healthcheck.ReadinessResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_tzworkflow.AdminReview": {
            "type": "object",
            "properties": {
                "decision": {
                    "type": "string"
                },
                "expert_report_comment": {
                    "type": "string"
                },
                "final_scorecard_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "review_feedback": {
                    "type": "string"
                },
                "review_submission_id": {
                    "type": "string"
                },
                "reviewed_at": {
                    "type": "string"
                },
                "reviewed_by_user_id": {
                    "type": "string"
                }
            }
        },
        "internal_tzworkflow.ChatMessage": {
            "type": "object",
            "properties": {
                "chat_session_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata_json": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "internal_tzworkflow.ChatSession": {
            "type": "object",
            "properties": {
                "analysis_run_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by_user_id": {
                    "type": "string"
                },
                "document_version_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_tzworkflow.CreateChatSessionRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string",
                    "minLength": 2
                }
            }
        },
        "internal_tzworkflow.CreateProjectRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "organization_name": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "minLength": 2
                }
            }
        },
        "internal_tzworkflow.CreateReportExportRequest": {
            "type": "object",
            "required": [
                "export_type",
                "review_submission_ids"
            ],
            "properties": {
                "export_type": {
                    "type": "string"
                },
                "review_submission_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_tzworkflow.CreateVersionRequest": {
            "type": "object",
            "required": [
                "file_id"
            ],
            "properties": {
                "file_id": {
                    "type": "string"
                }
            }
        },
        "internal_tzworkflow.DocumentVersion": {
            "type": "object",
            "properties": {
                "analysis_run_id": {
                    "type": "string"
                },
                "analysis_status": {
                    "type": "string"
                },
                "content_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "extraction_status": {
                    "type": "string"
                },
                "file_size_bytes": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "original_file_id": {
                    "type": "string"
                },
                "original_filename": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "raw_text_preview": {
                    "type": "string"
                },
                "uploaded_by_user_id": {
                    "type": "string"
                },
                "version_number": {
                    "type": "integer"
                }
            }
        },
        "internal_tzworkflow.LatestAnalysisResponse": {
            "type": "object",
            "properties": {
                "analysis": {
                    "$ref": "#/definitions/ai.AnalyzeResponse"
                },
                "analysis_run_id": {
                    "type": "string"
                }
            }
        },
        "internal_tzworkflow.Project": {
            "type": "object",
            "properties": {
                "active_version_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "final_version_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "organization_name": {
                    "type": "string"
                },
                "owner_user_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_tzworkflow.ReportExport": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by_user_id": {
                    "type": "string"
                },
                "export_type": {
                    "type": "string"
                },
                "file_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_tzworkflow.ReviewDecisionRequest": {
            "type": "object",
            "required": [
                "decision"
            ],
            "properties": {
                "decision": {
                    "type": "string",
                    "enum": [
                        "approved",
                        "rejected",
                        "needs_revision"
                    ]
                },
                "expert_report_comment": {
                    "type": "string"
                },
                "final_scorecard": {
                    "$ref": "#/definitions/ai.Scorecard"
                },
                "review_feedback": {
                    "type": "string"
                }
            }
        },
        "internal_tzworkflow.ReviewSubmission": {
            "type": "object",
            "properties": {
                "document_version_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                },
                "submitted_by_user_id": {
                    "type": "string"
                }
            }
        },
        "internal_tzworkflow.SendChatMessageRequest": {
            "type": "object",
            "required": [
                "user_message"
            ],
            "properties": {
                "user_message": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "internal_tzworkflow.SendChatMessageResponse": {
            "type": "object",
            "properties": {
                "ai_response": {
                    "$ref": "#/definitions/ai.ChatResponse"
                },
                "assistant_message": {
                    "$ref": "#/definitions/internal_tzworkflow.ChatMessage"
                },
                "session_id": {
                    "type": "string"
                },
                "user_message": {
                    "$ref": "#/definitions/internal_tzworkflow.ChatMessage"
                }
            }
        },
        "internal_tzworkflow.SubmitForReviewRequest": {
            "type": "object",
            "properties": {
                "document_version_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Satpayev Science TZ Backend API",
	Description:      "JWT Token as Bearer: Authorization: Bearer {token}",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
